// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/client.go -destination=internal/mocks/storage/client_mock.go -package=storage_mock
//

// Package storage_mock is a generated GoMock package.
package storage_mock

import (
	sql "database/sql"
	reflect "reflect"

	storage "github.com/cristianoliveira/aerospace-marks/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockDBResult is a mock of DBResult interface.
type MockDBResult struct {
	ctrl     *gomock.Controller
	recorder *MockDBResultMockRecorder
	isgomock struct{}
}

// MockDBResultMockRecorder is the mock recorder for MockDBResult.
type MockDBResultMockRecorder struct {
	mock *MockDBResult
}

// NewMockDBResult creates a new mock instance.
func NewMockDBResult(ctrl *gomock.Controller) *MockDBResult {
	mock := &MockDBResult{ctrl: ctrl}
	mock.recorder = &MockDBResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBResult) EXPECT() *MockDBResultMockRecorder {
	return m.recorder
}

// LastInsertId mocks base method.
func (m *MockDBResult) LastInsertId() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastInsertId")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastInsertId indicates an expected call of LastInsertId.
func (mr *MockDBResultMockRecorder) LastInsertId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastInsertId", reflect.TypeOf((*MockDBResult)(nil).LastInsertId))
}

// RowsAffected mocks base method.
func (m *MockDBResult) RowsAffected() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RowsAffected")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RowsAffected indicates an expected call of RowsAffected.
func (mr *MockDBResultMockRecorder) RowsAffected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RowsAffected", reflect.TypeOf((*MockDBResult)(nil).RowsAffected))
}

// MockStorageDBClient is a mock of StorageDBClient interface.
type MockStorageDBClient struct {
	ctrl     *gomock.Controller
	recorder *MockStorageDBClientMockRecorder
	isgomock struct{}
}

// MockStorageDBClientMockRecorder is the mock recorder for MockStorageDBClient.
type MockStorageDBClientMockRecorder struct {
	mock *MockStorageDBClient
}

// NewMockStorageDBClient creates a new mock instance.
func NewMockStorageDBClient(ctrl *gomock.Controller) *MockStorageDBClient {
	mock := &MockStorageDBClient{ctrl: ctrl}
	mock.recorder = &MockStorageDBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageDBClient) EXPECT() *MockStorageDBClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorageDBClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageDBClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorageDBClient)(nil).Close))
}

// GetDB mocks base method.
func (m *MockStorageDBClient) GetDB() *sql.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockStorageDBClientMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockStorageDBClient)(nil).GetDB))
}

// GetStorageConfig mocks base method.
func (m *MockStorageDBClient) GetStorageConfig() storage.StorageConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageConfig")
	ret0, _ := ret[0].(storage.StorageConfig)
	return ret0
}

// GetStorageConfig indicates an expected call of GetStorageConfig.
func (mr *MockStorageDBClientMockRecorder) GetStorageConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageConfig", reflect.TypeOf((*MockStorageDBClient)(nil).GetStorageConfig))
}

// MockDatabaseConnector is a mock of DatabaseConnector interface.
type MockDatabaseConnector struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseConnectorMockRecorder
	isgomock struct{}
}

// MockDatabaseConnectorMockRecorder is the mock recorder for MockDatabaseConnector.
type MockDatabaseConnectorMockRecorder struct {
	mock *MockDatabaseConnector
}

// NewMockDatabaseConnector creates a new mock instance.
func NewMockDatabaseConnector(ctrl *gomock.Controller) *MockDatabaseConnector {
	mock := &MockDatabaseConnector{ctrl: ctrl}
	mock.recorder = &MockDatabaseConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseConnector) EXPECT() *MockDatabaseConnectorMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockDatabaseConnector) Connect() (storage.StorageDBClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(storage.StorageDBClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockDatabaseConnectorMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDatabaseConnector)(nil).Connect))
}
