// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cristianoliveira/aerospace-ipc/pkg/client (interfaces: AeroSpaceSocketConn)
//
// Generated by this command:
//
//	mockgen -package aerospacecli_mock github.com/cristianoliveira/aerospace-ipc/pkg/client AeroSpaceSocketConn
//

// Package aerospacecli_mock is a generated GoMock package.
package aerospacecli_mock

import (
	reflect "reflect"

	client "github.com/cristianoliveira/aerospace-ipc/pkg/client"
	gomock "go.uber.org/mock/gomock"
)

// MockAeroSpaceSocketConn is a mock of AeroSpaceSocketConn interface.
type MockAeroSpaceSocketConn struct {
	ctrl     *gomock.Controller
	recorder *MockAeroSpaceSocketConnMockRecorder
	isgomock struct{}
}

// MockAeroSpaceSocketConnMockRecorder is the mock recorder for MockAeroSpaceSocketConn.
type MockAeroSpaceSocketConnMockRecorder struct {
	mock *MockAeroSpaceSocketConn
}

// NewMockAeroSpaceSocketConn creates a new mock instance.
func NewMockAeroSpaceSocketConn(ctrl *gomock.Controller) *MockAeroSpaceSocketConn {
	mock := &MockAeroSpaceSocketConn{ctrl: ctrl}
	mock.recorder = &MockAeroSpaceSocketConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAeroSpaceSocketConn) EXPECT() *MockAeroSpaceSocketConnMockRecorder {
	return m.recorder
}

// CheckServerVersion mocks base method.
func (m *MockAeroSpaceSocketConn) CheckServerVersion(serverVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckServerVersion", serverVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckServerVersion indicates an expected call of CheckServerVersion.
func (mr *MockAeroSpaceSocketConnMockRecorder) CheckServerVersion(serverVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckServerVersion", reflect.TypeOf((*MockAeroSpaceSocketConn)(nil).CheckServerVersion), serverVersion)
}

// CloseConnection mocks base method.
func (m *MockAeroSpaceSocketConn) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockAeroSpaceSocketConnMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockAeroSpaceSocketConn)(nil).CloseConnection))
}

// GetSocketPath mocks base method.
func (m *MockAeroSpaceSocketConn) GetSocketPath() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSocketPath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSocketPath indicates an expected call of GetSocketPath.
func (mr *MockAeroSpaceSocketConnMockRecorder) GetSocketPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSocketPath", reflect.TypeOf((*MockAeroSpaceSocketConn)(nil).GetSocketPath))
}

// SendCommand mocks base method.
func (m *MockAeroSpaceSocketConn) SendCommand(command string, args []string) (*client.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommand", command, args)
	ret0, _ := ret[0].(*client.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCommand indicates an expected call of SendCommand.
func (mr *MockAeroSpaceSocketConnMockRecorder) SendCommand(command, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommand", reflect.TypeOf((*MockAeroSpaceSocketConn)(nil).SendCommand), command, args)
}
