// Code generated by MockGen. DO NOT EDIT.
// Source: pkgs/aerospacecli/main.go
//
// Generated by this command:
//
//	mockgen -source=pkgs/aerospacecli/main.go -destination=internal/mocks/aerospacecli/main_mock.go -package=aerospacecli_mock
//

// Package aerospacecli_mock is a generated GoMock package.
package aerospacecli_mock
