name: On demand Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next version to bump to (e.g., v1.2.3)'
        required: true
        type: string
  # Upon a new tag creation
  push:
    tags:
      - 'v*.*.*'  # Adjust the pattern as needed

permissions:
  contents: write
  packages: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate new hashes based on version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            version="${{ inputs.version }}"
          else
            version=$(git describe --tags --abbrev=0)
          fi
          echo "Using version: $version"
          sed -i 's#version = ".*";#version = "'"$version"'";#' nix/package-default.nix
          sed -i 's#VERSION =.*#VERSION = "'"$version"'"#' cmd/root.go
          bash scripts/update-nix-hash.sh nix/package-default.nix ".#default"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to ${{ inputs.version }}"
          branch: bump-version-${{ inputs.version }}
          title: "chore: bump version to ${{ inputs.version }}"
          body: |
            This PR bumps the version to ${{ inputs.version }} and updates the necessary hashes.
          labels: version-bump
          draft: false
          base: main
          delete-branch: true
