name: Reset Nightly Branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Make sure to clone with at least last and before last commits
          fetch-depth: 2

      - name: reset nightly branch
        uses: nicksnell/action-reset-repo@master
        with:
          base_branch: main
          reset_branch: nightly

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes outside nix/
        id: changes_check
        run: |
          bash scripts/git-has-changes.sh >> $GITHUB_ENV

      - name: Generate new hashes
        if: env.has_code_changes == 'true'
        run: |
          bash scripts/update-nix-hash.sh nix/package-nightly.nix ".#nightly"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(nix): bump nightly hashes and version"
          title: "chore(nix): bump nightly hashes and version"
